POST http://localhost:8000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtamF5c3RhckBnbWFpbC5jb20iLCJleHAiOjE3MTA3MjM5NjIsInVzZXJJZCI6MX0.fz8XLoC58PipnJWVgNyZ_kkQqUKCjkiRaVX83f1bfAc

{
    "name": "Event Test Ant",
    "description": "This is a dummy description",
    "location": "Iwo, Nigeria",
    "date_time": "2023-04-10T13:20:54.000Z"
}
