DELETE http://localhost:8000/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtamF5c3RhQGdtYWlsLmNvbSIsImV4cCI6MTcxMDcwNTc5OSwidXNlcklkIjoyfQ.py_XGFh1b8SYShYN5KOpUrC2E0zkDlhYCw-C07bZA9A