PUT http://localhost:8000/events/7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtamF5c3RhQGdtYWlsLmNvbSIsImV4cCI6MTcxMDcwNjc2NywidXNlcklkIjoyfQ.oLMo9zWl3tL_5sTzP8JcBcE6jXyZglKDNWTfkUzRjOY

{
    "name": "Event Test Theree",
    "description": "This is a dummy description for this event",
    "location": "Iwo, Nigeria",
    "date_time": "2023-04-10T13:20:54.000Z"
}
